// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeFile(arg1:string):Promise<any>;

export function GetBitPlaneImages(arg1:string):Promise<Array<string>>;

export function GetForensicFilters(arg1:string):Promise<Array<main.FilterResult>>;

export function RepairAndSave(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;
