// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeFile(arg1) {
  return window['go']['main']['App']['AnalyzeFile'](arg1);
}

export function GetAudioSpectrogram(arg1) {
  return window['go']['main']['App']['GetAudioSpectrogram'](arg1);
}

export function GetBitPlaneImages(arg1) {
  return window['go']['main']['App']['GetBitPlaneImages'](arg1);
}

export function GetForensicFilters(arg1) {
  return window['go']['main']['App']['GetForensicFilters'](arg1);
}

export function RepairAndSave(arg1) {
  return window['go']['main']['App']['RepairAndSave'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
